PR Milestone 2: Components and Redux store
pastorp3/BookStore pull request #2
Opened 2021-04-09 18:46 UTC by pastorp3

## Book Store Milestone 2: Components and Redux store

In this PR I:
- Crete redux store
- Set reducer
- Create actions
- Add components to display the current state
- Integrate redux with components

2021-04-09 20:02 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello @pastorp3 👋🏾 
Congratulations on submitting the second milestone for this project for review. Take note of the following required changes before we proceed. For this milestone, we need to make sure the correct order of where we place our code is followed.

### Mandatory
- [x] Move the `App.js` to the `components` directory.
- [x] Add the missing book `id` in the `book` component.
- [ ] Move the `bookList.js` and the `bookForm.js` components to the container directory.
- [ ] Move the `actions` and `reducers` directories to the src directory.

### Happy coding 💻 
#### Christian Otieno (CR)

2021-04-09 20:02 UTC, christianotieno commented on src/App.js
>  import './App.css';
## Move the app component
- [ ] The `App.js` component needs to be moved to the `src/components` directory.

2021-04-09 20:02 UTC, christianotieno commented on src/App.js
>  function App() {
## Employ the use of ES6 syntax
- [ ] Do you mind implementing this functional declaration using the `ES6` arrow syntax?

2021-04-09 20:02 UTC, christianotieno commented on src/components/book/book.js
> +);
## Implement the missing book id section 
- [ ] Our `book` component should represent a single row of books with `id`, `title` and `category` [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/Book/RepresentARowInBooksTable.png). We are currently missing the `id` part, lets add it.

2021-04-09 20:02 UTC, christianotieno commented on src/components/booksForm/booksForm.js
> +/* eslint-disable arrow-body-style */
## Move the book component
- [ ] The `bookForm.js` component needs to be moved to the `container` directory. You only need to have the `App.js` and the `book.js` components in this directory.

2021-04-09 20:02 UTC, christianotieno commented on src/components/booksForm/booksForm.js
> +  };
## Implement the missing book id section 
- [ ] Our `book` component should represent a single row of books with `id`, `title` and `category` [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/Book/RepresentARowInBooksTable.png). We are currently missing the `id` part, let's implement it here. We can have this by generating a random number to act as our `id` whenever a book gets created. that's one way to do it.

2021-04-09 20:02 UTC, christianotieno commented on src/components/booksList/booksList.js
> +/* eslint-disable arrow-body-style, max-len, react/forbid-prop-types */
## Move the bookList component
- [ ] The `bookList.js` component needs to be moved to the `container` directory. You only need to have the `App.js` and the `book.js` components in this directory.

2021-04-09 20:02 UTC, christianotieno commented on src/containers/actions/index.js
> +
## Move the action files
- [ ] The `action.js` module needs to be moved to the `src` directory. You only need to have the `bookForm.js` and the `bookList.js` components in this directory.

2021-04-09 20:02 UTC, christianotieno commented on src/containers/reducers/book.js
> +/* eslint-disable no-return-assign */
## Move the reducer directory
- [ ] The `reducer` directory needs to be moved to the `src` directory. You only need to have the `bookForm.js` and the `bookList.js` components in this directory.

2021-04-10 01:03 UTC, uche-inyama requested changes
## Changes Required

### Hi @pastorp3 :wave: 

* [ ] What is left from the changes requested from the previous reviewer is the **id**, in the book object. The book object that is created in the bookform component should look like so:


```
  addBook({
    id: generateID(),
    title,
    category
  });
```
You can use the [uuid package](https://www.npmjs.com/package/uuid) to generate the random ids.

#### Make this change, then submit another form for a code review


### Happy Coding :technologist: 

#### ``` Uchechukwu Henry inyama ```

2021-04-10 09:30 UTC, wathigo approved these changes
## APPROVED :heavy_check_mark:  
Great job implementing the suggested changes.
All requirements have been met.

**You may proceed to the next milestone.**

**Happy Coding :computer: 
Simon Wathigo**

2021-04-10 20:54 UTC, merged